"""POST /export/pdf — the conversation as a KSP-letterhead PDF.

Renders from data.conversation_turn (the plaintext content store), NOT from
audit_log, which holds only hashes.

The renderer is **Catalyst SmartBrowz** (`convert_to_pdf`) — the platform's headless
browser service. The local headless-Chrome path below it is kept as the offline
fallback only: it is what runs under `docker compose up` and in the test suite, where
there is no Catalyst project to call. When neither is reachable we return the
print-ready HTML with a header saying so, rather than failing the export or shipping
a fake PDF — an officer can still print it from the browser.
"""
import html
import os
import shutil
import subprocess
import tempfile

from data import get_conversation_history
from fastapi import APIRouter, Depends, HTTPException, Response, status
from pydantic import BaseModel

from ..audit import record
from ..auth.jwt_auth import Officer, current_officer

router = APIRouter()


class ExportRequest(BaseModel):
    session_id: str


_CSS = """
body{font-family:'Segoe UI',Arial,sans-serif;margin:40px;color:#111}
.hdr{border-bottom:3px solid #16264a;padding-bottom:12px;margin-bottom:24px}
.hdr h1{margin:0;font-size:20px;color:#16264a;letter-spacing:.5px}
.hdr .sub{font-size:12px;color:#556}
.turn{margin:22px 0;page-break-inside:avoid}
.q{font-weight:600;color:#16264a}
.a{margin:8px 0;white-space:pre-wrap;line-height:1.5}
.cites{font-size:11px;color:#445;border-left:3px solid #ccd;padding-left:10px;margin-top:8px}
.foot{margin-top:36px;font-size:10px;color:#889;border-top:1px solid #ddd;padding-top:8px}
"""


def _render_html(session_id: str, officer: Officer, turns) -> str:
    parts = [
        "<!doctype html><meta charset='utf-8'>",
        f"<style>{_CSS}</style>",
        "<div class='hdr'><h1>KARNATAKA STATE POLICE</h1>",
        "<div class='sub'>Veritas Crime Intelligence Platform — Conversation Record</div>",
        f"<div class='sub'>Officer: {html.escape(officer.name)} ({html.escape(officer.badge_no)}, "
        f"{html.escape(officer.role)}) &middot; Session: {html.escape(session_id)}</div></div>",
    ]
    for t in turns:
        parts.append("<div class='turn'>")
        parts.append(f"<div class='q'>Q{t.turn_index + 1}. {html.escape(t.query)}</div>")
        parts.append(f"<div class='a'>{html.escape(t.final_answer)}</div>")
        if t.citations:
            cites = "<br>".join(
                f"[{c.get('index')}] {html.escape(str(c.get('label','')))}" for c in t.citations)
            parts.append(f"<div class='cites'>{cites}</div>")
        parts.append("</div>")
    parts.append("<div class='foot'>Generated by Veritas. Every statement above is "
                 "traceable to the cited record. Decision-support only.</div>")
    return "".join(parts)


def _find_browser() -> str | None:
    """A Chromium-family browser, on PATH or at its usual install location.

    Chrome and Edge are almost never on PATH on Windows, so a which()-only lookup
    silently downgrades every export to HTML on the exact machine the demo runs on.
    """
    if os.getenv("VERITAS_CHROME"):
        return os.getenv("VERITAS_CHROME")
    for name in ("chrome", "chromium", "google-chrome", "msedge"):
        found = shutil.which(name)
        if found:
            return found
    for path in (
        r"C:\Program Files\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
        r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
        "/usr/bin/google-chrome", "/usr/bin/chromium",
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    ):
        if os.path.exists(path):
            return path
    # Last resort: Playwright's bundled Chromium (a dev dependency of this repo).
    # Same binary family, same CLI flags — so a machine with no system browser
    # still exports a real PDF instead of downgrading to HTML.
    try:
        from playwright.sync_api import sync_playwright
        with sync_playwright() as p:
            if os.path.exists(p.chromium.executable_path):
                return p.chromium.executable_path
    except Exception:
        pass
    return None


def _smartbrowz_pdf(page: str) -> bytes | None:
    """Catalyst SmartBrowz render. Returns None when Catalyst isn't configured here."""
    from ..auth.catalyst_auth import enabled
    if not enabled():
        return None
    try:
        import zcatalyst_sdk
        app = zcatalyst_sdk.initialize()
        # A4, KSP letterhead margins. The HTML is the same string the local renderer
        # gets, so the two paths cannot drift into producing different documents.
        return app.smartbrowz().convert_to_pdf(page, pdf_options={
            "format": "A4",
            "margin": {"top": "15mm", "bottom": "15mm", "left": "12mm", "right": "12mm"},
            "print_background": True,
        })
    except Exception:
        # A PDF export is not worth 500-ing a session over — fall through to the
        # local renderer, and to HTML below that.
        return None


def _local_pdf(page: str) -> bytes | None:
    """Headless Chrome render. Returns None when no browser is installed."""
    chrome = _find_browser()
    if not chrome:
        return None
    with tempfile.TemporaryDirectory() as tmp:
        src = os.path.join(tmp, "doc.html")
        out = os.path.join(tmp, "doc.pdf")
        with open(src, "w", encoding="utf-8") as f:
            f.write(page)
        try:
            subprocess.run(
                [chrome, "--headless", "--disable-gpu", "--no-sandbox",
                 f"--print-to-pdf={out}", "--no-pdf-header-footer", f"file://{src}"],
                check=True, timeout=60, capture_output=True)
            with open(out, "rb") as f:
                return f.read()
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired, OSError):
            return None


@router.post("/export/pdf")
async def export_pdf(req: ExportRequest, officer: Officer = Depends(current_officer)):
    turns = get_conversation_history(req.session_id)
    if not turns:
        raise HTTPException(status.HTTP_404_NOT_FOUND, "No conversation for this session")

    page = _render_html(req.session_id, officer, turns)
    pdf = _smartbrowz_pdf(page) or _local_pdf(page)
    record(officer.officer_id, req.session_id, "/export/pdf",
           req.model_dump(), {"turns": len(turns), "pdf": bool(pdf)})

    if pdf:
        return Response(pdf, media_type="application/pdf", headers={
            "Content-Disposition": f'attachment; filename="veritas-{req.session_id[:8]}.pdf"'})
    return Response(page, media_type="text/html", headers={"X-Veritas-Pdf": "unavailable"})
